### ISSUE TITLE
Questions about 1.0 and the wiki

### ISSUE THREAD

**Issue by sheriffderek** [LearnBoost/stylus#1860]
# How *real* is the road map in the wiki?

If it was over a year since the wiki was edited - and there are only 2 revisions, how well does this describe the community's feelings or the direction of the parties who are maintaining stylus?

I absolutely *love* working with stylus and autoprefixer. Besides a few little things I was doing in SCSS, *which I don't really need anyways*, stylus does everything I want - and makes me extremely happy on a daily basic. Sometimes I just sit and smile about how wonderful life is because of stylus.

376 on the Emmet repo - Made me start thinking about a few things.
https://github.com/emmetio/emmet/pull/376#issuecomment-81814236

Currently, there are a few things that just don't work how I might expect in stylus... and so currently,  I just put the CSS or SCSS in there - and it works. `::selection` I think is one of them if I remember correctly...  Or say I need to pull over a large set of simple SCSS in a hurry - I can leave it how it is until I have time to reformat it - *and when I do* - I can quickly and easily find and delete the `: ` ` {` and `}`

It is much easier to delete those things than it would be - to paste `:` across all of my projects after the fact. I'm not going to try and sway it either way. I personally think that it's easier to write and *read* without the `:` - but I care much more about just knowing how likely the things mentioned in the 1.0 wiki - will actually happen. If so I will start using `:` in all my code immediately - without complaint. This is just a single example from that list of things though.

Is anyone in a place where they can split up the wiki / *road map* into sections of likelihood - or does anyone have any more current thoughts on this subject? I may not understand the larger picture - and the code base - but I use stylus all day - and I love it - and I like the way it is.

It seems like a 

`shift` > `:` > `space` 
vs 
`space` 

issue... *and one of those if definitely less key strokes than the other...*

If the `:` becomes mandatory - I'll just get my syntax highlighter to dull it out a bit and be happy as a clam.   : )

I just want to know sooner than later. Thanks.

**Comment by corysimmons** [comment]
I used to use the colon-less syntax until a few key members (@declandewet @jenius etc.) of the community pointed out that most libraries use the colon syntax as it provides a clearer separation between `key: val`.

I didn't like it at the time, but I took the community's advice and converted my libraries and have preferred the colon syntax since then.

The fact that Stylus allows so many variations on the syntax is a novelty, but it's not necessarily good for the language to write it in a bunch of different ways. It looks really bad when I'm on a project that is using a few different syntaxes and makes it hard to visually parse what's going on from context to context.

To answer your question, I'm pretty sure it will become mandatory at `rc-1.0` but @kizu and @Panya (2 core maintainers to Stylus) would be better suited to reaffirm this position.

In the meantime, I'm going to continue trying to gain support for a consistent syntax across the board whatever syntax that may be. But as it stands, it looks like colon separation will be the syntax of choice.

@kizu Is `$var` going to become a mandatory syntax as well?

**Comment by Panya** [comment]
@sheriffderek  yep, we pretty sure that `:` wouldn't be optional. Actually you can try to compile your code with changes in `rc-1.0` (checkout the repo and change branch to `rc-1.0` then run `./bin/stylus <your-file>` ).

@corysimmons 
> @kizu Is $var going to become a mandatory syntax as well?

We're not sure about this, now in `rc-1.0` we have a special behavior for vars with `$` (we throw an error if you're trying to use the var without declaring it). But old syntax is supported too.

**Comment by kizu** [comment]
> Is `$var` going to become a mandatory syntax as well?

Yes, I think that we would keep the $-less variables for 1.0, as the transparent nature of things in Stylus is a widely-used feature and it would be not that wise to lose it. But as @Panya have said, we would surely improve the way the `$` vars work: other than throwing the errors they would also give you false when used undeclared in comparisons and other stuff like that. While $-less variables would still fallback to the keywords.
